config/urls.py
from django.contrib import admin
from django.urls import path, include

# Loading images on development mode
from django.conf.urls.static import static
from django.conf import settings

from django.views.static import serve

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include

from .views import *

app_name = 'core'
urlpatterns = [
    path('', about, name='about'),
    path('skills/', skills, name='skills'),
    path('contact/', contact, name='contact'),
    path('success/', success, name='success'),
]

core/models.py
from django.db import models


class Skill(models.Model):
    name = models.CharField('Título', max_length=100)
    description = models.TextField('Descrição', blank=True)
    experience = models.CharField('Experiência', max_length=5, blank=True)
    img = models.ImageField(upload_to='skills/image', verbose_name='Imagem', null=True, blank=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'
        ordering = ['created_at']
    

core/forms.py
from django import forms


class ContactForm(forms.Form):
    from_email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'E-mail'}), required=True, label='')
    subject = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Assunto'}), required=True)
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Mensagem'}), required=True)

core/views.py
from django.shortcuts import render, redirect

from .models import Skill

# Email Form
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm


def about(request):
    template_name = 'about.html'
    return render(request, template_name)


def skills(request):
    skills = Skill.objects.all()
    template_name = 'skills.html'
    context = {
        'skills': skills
    }
    return render(request, template_name, context)


def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['felix.botta@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('core:success')
    return render(request, "contact.html", {'form': form})


def success(request):
    template_name = 'success.html'
    return render(request, template_name)

core/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div id="wrapper">
    <img src="https://avatars2.githubusercontent.com/u/60927161?s=400&u=dfd98db169c997029141775f7e9a9e1f9f1f864a&v=4"
         alt="Felix Botta">
    <h1>Felix Botta</h1>

    <h2>Desenvolvedor Python</h2>
    <p>Formado em Análise e Desenvolvimento de Sistemas sou apaixonado por tecnologia e desenvolvimento de software.
        Entusiasta e autodidata, sempre disposto a aprender e aplicar novos conceitos para superar os desafios.

        <a href="https://github.com/felixbotta" target="_blank">Github</a></p>
</div>
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Felix Botta</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
<body>
<header>
    <div class="links">
        <a href="{% url 'core:about' %}">Sobre</a>
        <a href="{% url 'core:skills' %}">Skills</a>
        <a href="{% url 'core:contact' %}">Contato</a>

    </div>
</header>
{% block content %}{% endblock %}

<div id="links-footer" class="links">
    <a href="https://github.com/felixbotta" target="_blank">Github</a>
    <a href="mailto:felix.botta@gmail.com">E-mail</a>
    <a href="https://linkedin.com/in/felix-botta" target="_blank">Linkedin</a>
</div>
</body>
</html>

core/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact Us{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div id="contact">

    <h3 class="form_title">Contato</h3>

    <form class="form" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-actions">

            <button type="submit" class="btn btn-success">Enviar</button>

        </div>
    </form>
</div>
{% endblock %}

core/templates/skills.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div id="wrapper">
    <h1>Skills</h1>
</div>

<section class="cards">
    {% for skill in skills %}
    <div class="card">
        <div class="card_image_container">
            <img src="{{ skill.img.url }}" alt="{{ skill.name }}" height="250px" width="400px" />
        </div>
        <div class="card_content">
            <p>{{ skill.name }}</p>
        </div>
        <div class="card_info">
            <p>{{ skill.description }}</p>
            <p class="card_star">{{ skill.experience }}</p>
        </div>
    </div>
    {% empty %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <div class="l-box">
                <p>No skill registered.</p>
            </div>
        </div>
    </div>
    {% endfor %}
</section>

{% endblock %}

core/templates/success.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="sent_email">

    <h3>Mensagem Enviada</h3>

    <div class="sent_email_img">
        <img src="{% static 'img/sent-email.png' %}" height="175px" width="175px" alt="Sent Email"/>
    </div>

</div>
{% endblock %}